### ISSUE TITLE
mariadb-plugin-rocksdb not found/not installed in docker containers in vmnet

### ISSUE THREAD

**Issue by Mat001** [Lamden/cilantro#138]
When I run `python tests/vmnet/test_bootstrap.py` in PyCharm I get 

`Step 8/10 : RUN mariadb-plugin-rocksdb`
`---> Running in ca6bfd39c7a7`
`/bin/sh: 1: mariadb-plugin-rocksdb: not found`
`The command '/bin/sh -c mariadb-plugin-rocksdb' returned a non-zero code: 127`

Apparently there is no existing plugin mariadb-plugin-rocksdb on Ubuntu 16.04 (which runs in containers).
Mariadb gets installed nicely and so do all other packages.

Makes me wonder if you guys have vmnet smoke tests working. And if so, is it with or without myrocks plugin?

PS: I wasn't able to get this working I get a different error, but may be related. Can discuss separately.
@wywfalcon

**Comment by Mat001** [comment]
Replication step to get he console output specifically for myrocks:
in dockerfile `cilantro_base.dev` separate installs for mariadb and myrocks
    
Change this `&& apt-get install -y mariadb-server mariadb-plugin-rocksdb \`

into this

`RUN apt-get install -y mariadb-server`
`RUN mariadb-plugin-rocksdb`

**Comment by wywfalcon** [comment]
thanks for waiting, I will look into it now

**Comment by wywfalcon** [comment]
Sorry, it seems that the image-build is not working now and we need to add seneca for the new image. Due to MariaDB 10.2 now including RocksDB out of the box, we can now have a more stable image build. Also I'll be using alpine as it is smaller and now overall simpler. Let me update you once things become stable.

**Comment by wywfalcon** [comment]
@Mat001 Everything has been updated and now for vmnet-integrated test test_secure_connection.py will work but others involving consensus and seneca still needs to be tested :( unfortunately

**Comment by StuartFarmer** [comment]
Closing this issue. Reopen it if there is a problem with the Seneca docker.
