### ISSUE TITLE
Do block have idempotent state changes or transactional history?

### ISSUE THREAD

**Issue by StuartFarmer** [Lamden/cilantro#33]
Decide whether or not to describe state changes in the blockchain with explicit transactions or just the end result change in balances and other variables during the current block.

**Comment by StuartFarmer** [comment]
AKA:

Block contains pure database query instructions or the transactions which then are calculated into database query instructions.

Either one should inform us how to traverse the blockchain to become in sync with the network.

**Comment by dhaba** [comment]
Can the ability to include transaction history be decided on a per-transaction basis as a metavariable? 

Not sure if this would make sense but putting this idea here for further digestion.

**Comment by TimothyWard** [comment]
I would argue for transactional history. Imagine a use case of algorithmic trading in which 100s of trades to/from the same wallet are being processed. Each comes with a transaction fee that also affects the total balance. Having the record of transactions is more inline with cryptocoin standard and will ease transparency/debugging in the future.
