### ISSUE TITLE
Complete loop of the system - Host some nodes

### ISSUE THREAD

**Issue by abutenkolamden** [Lamden/cilantro#394]

**Comment by StuartFarmer** [comment]
@abutenkolamden I'm going to move this to next sprint. I need to do a feature before this that I had not foreseen in the sprint planning. Same goes for some of the other issues I'm moving to done.

**Comment by abutenkolamden** [comment]
Oh, can you please move them not to "Done" but to "Next Sprint"? 

As I don't know what of your issues are actually not done but should be planned for the next sprint. I move this issue to next sprint, please move others.

**Comment by abutenkolamden** [comment]
will be tracked in Trello now
