### ISSUE TITLE
Documentation - Overview of the system

### ISSUE THREAD

**Issue by abutenkolamden** [Lamden/cilantro#398]
Feedback from team may drive the scope of work 

Acceptance criteria - confirmation from other team members (at least Jeff) that documentation is Ok to understand the product for a new developer.

**Comment by JeffWScott** [comment]
@raghupc which part of the doco would you say this is supposed to cover off?

**Comment by raghupc** [comment]
I guess it is filed initially as the master task covering entire documentation.

**Comment by abutenkolamden** [comment]
@JeffWScott can we close this?

**Comment by JeffWScott** [comment]
@abutenkolamden yes, it looks like all other Documentation items have been passed so go ahead and close this
