### ISSUE TITLE
Upgrade Module - command line

### ISSUE THREAD

**Issue by abutenkolamden** [Lamden/cilantro#401]
- command to trigger upgrade contract
- command to generate pepper
- command to register vote

Acceptance criteria - Test / Demo

**Comment by davetejas** [comment]
TJ-MAC:commands tej$ python3 cmd.py -h
usage: cil [-h] {update} ...

Lamden Commands

optional arguments:
  -h, --help  show this help message and exit

subcommands:
  Network update commands

  {update}    Shows set of update cmd options
TJ-MAC:commands tej$ python3 cmd.py update -h
usage: cil update [-h] [-t [PKG_HASH]] [-v] [-r]

optional arguments:
  -h, --help            show this help message and exit
  -t [PKG_HASH], --trigger [PKG_HASH]
                        str: Notify network of new update with given pkg_hash
  -v, --vote            Bool : Register consent for network version upgrade
  -r, --ready           Bool : Notify network upgrade ready
TJ-MAC:commands tej$ python3 cmd.py update -v

**Comment by davetejas** [comment]
fixes already merged to rel_jan_2020
