### ISSUE TITLE
Upgrade Module (Phase 2) - Build package tar directory for distribution

### ISSUE THREAD

**Issue by abutenkolamden** [Lamden/cilantro#403]
Test

**Comment by davetejas** [comment]
TJ-MAC:scripts tej$ python3 pkg.py 
/Volumes/dev/lamden/cilantro-enterprise/cilantro_ee
Choose number for Package operation
1: Generate pepper
2: Verify Package
3: Verify current pepper hash
Enter Package operation: 1
9da86438441dbfafe1105ef16b3dfb0684ddf974e7984b109178ede78a4deea1

**Comment by davetejas** [comment]
commit : https://github.com/Lamden/cilantro-enterprise/commit/1ae6c99a1ec5299c5b96f6b7ab72cfefca2e397f

in release branch rel_jan_2020
