### ISSUE TITLE
Upgrade Module (Phase 2) - ready vote by node

### ISSUE THREAD

**Issue by abutenkolamden** [Lamden/cilantro#405]
Test with existing state

**Comment by davetejas** [comment]
update : 

- test cases need updated need to be compliant with new nbn arch

**Comment by davetejas** [comment]
Test output :
 Ready vote 

TJ-MAC:commands tej$ python3 cmd.py update -r
None False True
Namespace(pkg_hash=None, ready=True, vote=False)
TJ-MAC:commands tej$

**Comment by davetejas** [comment]
code 
https://github.com/Lamden/cilantro-enterprise/commit/608a4a966c7ac7d2eea5aae3bd8cfd825e977a7d

**Comment by abutenkolamden** [comment]
@davetejas thanks, just to confirm. task is done and can be closed?

**Comment by abutenkolamden** [comment]
confirmed. closing
