### ISSUE TITLE
Wallet IDE - Integrate Monaco Editor

### ISSUE THREAD

**Issue by abutenkolamden** [Lamden/cilantro#410]
Loading the editor is done after compile. Have to figure out how that's done in svelte

Acceptance Criteria - Editor loads when Smart Contract page is clicked.  Unloads when navigating away

**Comment by JeffWScott** [comment]
Monaco Editor loads in the IDE tab of the wallet. @abutenkolamden please close
![image](https://user-images.githubusercontent.com/4855017/73880067-aa872a80-482b-11ea-9591-864c179c0623.png)

**Comment by abutenkolamden** [comment]
@JeffWScott what about this last issue?
