### ISSUE TITLE
Wallet IDE - Persist open contracts across sessions

### ISSUE THREAD

**Issue by abutenkolamden** [Lamden/cilantro#411]
Create a new svelte store in the browser local storage

Acceptance Criteria - Tabs persist between sessions of the wallet

**Comment by JeffWScott** [comment]
Follow Install instructions @ wallet master: https://github.com/Lamden/wallet

Click the menu option "Smart Contracts".
Click the "+" button on the tab bar.  
Click "Start a new Contract".
Model will close and a new tab will open with some default code.  
Write in code window.  
Close wallet.
Open wallet
If "Smart Contracts" page doesn't open, click the menu option "Smart Contracts".
Check that the new tab still exists and the code you entered is correct.

**Comment by JeffWScott** [comment]
FilesStore implemented to persist open IDE files
All files store tests passing.
@abutenkolamden  please close

![image](https://user-images.githubusercontent.com/4855017/73879555-b7574e80-482a-11ea-9831-9daac70ffab9.png)
