### ISSUE TITLE
Wallet IDE - Load already submitted contracts from blockchain

### ISSUE THREAD

**Issue by abutenkolamden** [Lamden/cilantro#412]
- Get contract code from blockchain, store it in new file storage so it creates a new tab
- Handle tabs when network has changed or network goes offline

Acceptance Criteria:
- Contracts can be opened by specifying the name, they will be opened in a new tab and the code displayed in the editor window
- A dropdown with all currently stored networks should be available

**Comment by JeffWScott** [comment]
Click the "+" button on the tab bar. enter contract name in the "Contract Name" input box and click the "Open Contract" button.  

Model will close and new tab will open with contact code, methods (if any) will populate below the code window.

**Comment by JeffWScott** [comment]
FilesStore implemented to persist contracts opened from the blockchain in the IDE
All tests passing 
@abutenkolamden please close

![image](https://user-images.githubusercontent.com/4855017/73879631-d7870d80-482a-11ea-9878-0688cba7d157.png)
