### ISSUE TITLE
Wallet IDE - Integrate with Mockchain linting endpoint

### ISSUE THREAD

**Issue by abutenkolamden** [Lamden/cilantro#413]
- Get errors from the lint endpoint, handle the response objects correctly as well as displaying the errors on screen
- If possible show erros in the editor window with error line information

Acceptance Criteria: Clicking Lint will return a list of errors from the webserver.  Errors will be shown on the UI and mistakes highlighted in the editor window

**Comment by JeffWScott** [comment]
Follow Install instructions @ wallet master: https://github.com/Lamden/wallet

Click the "Smart Contracts" menu item
Click the "+" button on the tab row
Click "Start New Contract"

Click the "Check Contract" button on the bottom of the code window
"Contract is Okay" displayed below code window

remove "@export" from above function definition
"Line 0: S13- No valid contracting decorator found" displayed below code window in red

Add "@export" back to code window above function definition.
Click the "Check Contract" button on the bottom of the code window
"Contract is Okay" displayed below code window

Remove the colon from the end of the function definition.
Click the "Check Contract" button on the bottom of the code window
"def first_method(value)" highlighted in red.
hover over red highlighting creates a hover window with the displayed text "invalid syntax: def first_method(value)"
"Line[4:24]: invalid syntax" is displayed in red below code window

Creating any of these error situations and clicking the "Submit To Network" displays the same error info and prevents the "Submit Contract" model from opening.

**Comment by JeffWScott** [comment]
Linting tests passing.

@abutenkolamden this can be closed

![image](https://user-images.githubusercontent.com/4855017/73879144-efaa5d00-4829-11ea-8ea9-fcabed1f2381.png)
