### ISSUE TITLE
Wallet IDE - Ability to submit contracts from the IDE

### ISSUE THREAD

**Issue by abutenkolamden** [Lamden/cilantro#414]
Create all models and logic to submit the contracts

Acceptance Criteria:
- When the submit button is clicked a model will open with submission details
- Cannot submit a duplicate contract name
- Allows you to choose which wallet to submit with
- Allows you to set Stamp Limit
- Show you the transaction success / failure and associated info

**Comment by JeffWScott** [comment]
Follow Install instructions @ wallet master: https://github.com/Lamden/wallet

Click the "Smart Contracts" menu item
Enter valid smart contract code in a new tab
Click the "Submit to Network" button at the bottom on the code window
Submit Contract Model will open
Select a wallet with enough TAU to cover stamp cost
Change name of contract to a valid one.
Leave Optional boxes empty
Click "ConfirmTransaction"
Transaction result will be displayed.

**Comment by JeffWScott** [comment]
Awaiting TransactionBuilder tests

@abutenkolamden keep this open here or migrate to Trello

**Comment by abutenkolamden** [comment]
@JeffWScott let's keep here for a while, too many comments here.

**Comment by JeffWScott** [comment]
TransactionBuilder class 100% tested and passing
@abutenkolamden please move do done

![image](https://user-images.githubusercontent.com/4855017/73966430-f8f80000-48e3-11ea-9a12-90418bd853bd.png)
