### ISSUE TITLE
Wallet IDE - Ability to run methods of submitted contracts

### ISSUE THREAD

**Issue by abutenkolamden** [Lamden/cilantro#415]
Create all models and logic to submit a tx

Acceptance Criteria:
- When the "run method" button is clicked a model opens with all required information about the contract, method and arg values
- Allows you to choose which wallet to submit with
- Allows you to set Stamp Limit
- Show you the transaction success / failure and associated info

**Comment by JeffWScott** [comment]
Follow Install instructions @ wallet master: https://github.com/Lamden/wallet

Click the "Smart Contracts" menu item
Click the "+" button on the tabs row and open a smart contract from the network (ie currency)
Scroll to below the code window to the Contract Methods  section.  
fill in method arg info
click "run" beside the method name to open the tx confirm model
Click "confirm transaction"
see tx results displayed,

**Comment by JeffWScott** [comment]
Awaiting TransactionBuilder tests

@abutenkolamden keep this open here or migrate to Trello

**Comment by abutenkolamden** [comment]
@JeffWScott let's keep here for a while, too many comments here.

**Comment by JeffWScott** [comment]
@abutenkolamden TransactionBuilder tested and all test passing.  Please close.
![image](https://user-images.githubusercontent.com/4855017/73966290-bf26f980-48e3-11ea-9b57-fcbba7d5f2d5.png)
