### ISSUE TITLE
Wallet IDE - Ability to check veraiable state of submitted contracts

### ISSUE THREAD

**Issue by abutenkolamden** [Lamden/cilantro#416]
- Create all models and logic to check state. 
- require an endpoint to return variable names

Acceptance Criteria:
- When a key is entered in the input box beside the variable a value will be returned and shown on the UI

**Comment by JeffWScott** [comment]
@StuartFarmer need endpoint changes for this as we aren't returning variables currently.  
I think the plan we had discussed is to return a {name, code, methods, variables} object directly from the "contracts" endpoint. 

If you don't have time to get to this then I can attempt a solution later on.

**Comment by JeffWScott** [comment]
@abutenkolamden  Team didn't get around to creating the endpoints, Moving to Next sprint.

**Comment by abutenkolamden** [comment]
will be tracked in Trello now
