### ISSUE TITLE
Wallet Misc - Refresh balances from blockchain when appropriate as well as provide a manual refresh button

### ISSUE THREAD

**Issue by abutenkolamden** [Lamden/cilantro#419]
Acceptance Criteria:
- Limit the amount of balance calls to prevent overloading webserver
- Refresh button on main page allows user to  refresh balances manually.  Balances update when button is pressed

**Comment by JeffWScott** [comment]
Balance refreshing has been implemented but needs to be refactored to ensure we are not calling it too much.  This needs to be done next Sprint.

**Comment by abutenkolamden** [comment]
will be tracked in Trello now
