### ISSUE TITLE
What sort of meta data do we need to persist in a block's header? (in cold storage)

### ISSUE THREAD

**Issue by dhaba** [Lamden/cilantro#42]
Obviously we need the hash of a previous block, as well as the hash of the stored block. 

Do we also need to build a Merkle tree, and store the root? Time stamp? Bits (size of block)? Some kind of version # (corresponding to our build version)?

**Comment by TimothyWard** [comment]
In general, so long as the information being included does not come at an enormous compute or storage cost, I would say the more the merrier. Metadata in a requisite-linked structure like this has a way of being really handy later on for optimizations and/or security, and its much harder to add later given the downstream changes it would propagate.
