### ISSUE TITLE
Wallet Misc - Handle networks going offline, show status

### ISSUE THREAD

**Issue by abutenkolamden** [Lamden/cilantro#421]
- When a network is offline the IDE needs to handle the tab associated with a contract on the offline network properly so that errors don't get thrown

Acceptance Criteria - User can interact with all aspects of the wallet when they are on an offline network

**Comment by JeffWScott** [comment]
Progress is about 50% on this.  It will have to move to next Sprint.

**Comment by abutenkolamden** [comment]
will be tracked in Trello now
