### ISSUE TITLE
Wallet Misc - Testing

### ISSUE THREAD

**Issue by abutenkolamden** [Lamden/cilantro#423]
- Create transaction
- history screen
- dev tools screen
- switching networks

Acceptance Criteria: All tests pass

**Comment by JeffWScott** [comment]
The importing of Monaco editor seems to be breaking the cypress testing suite we were using for unit testing.

I have an issue open with the Cypress.io team and they are assisting.
I am also in the progress of investigating other ways to test Svelte apps.

I refactored the IDE code to move the importing of the Monaco editor out to it's own module.  This allows me to comment out the import and have the app still build and function correctly (but have no editor).  As a failback I can disable to Monaco editor and run all the test cases to test 99% of the app.

**Comment by JeffWScott** [comment]
@abutenkolamden Moving the creation of new testcases and fixing of cypress to next sprint

**Comment by abutenkolamden** [comment]
will be tracked in Trello now
