### ISSUE TITLE
Fix CORS issues on mockchain server - install and setup sanic-cors

### ISSUE THREAD

**Issue by abutenkolamden** [Lamden/cilantro#425]
Acceptance Criteria - API request from the broswer don't return CORS error

**Comment by JeffWScott** [comment]
Sanic-CORS setep.

@davetejas 
Testnet tokens faucet no longer throws CORS errors in browser console.
Test by minting tokens to vk 2beec8ccfed61af0e81aac2cc189721ec654e6322ed42209c3dfaf91c0808254 @ https://gracious-johnson-674531.netlify.com/

check balance increases by clicking the below link:
https://testnet.lamden.io/contracts/currency/balances/?key=2beec8ccfed61af0e81aac2cc189721ec654e6322ed42209c3dfaf91c0808254
