### ISSUE TITLE
Documentation - explain stop protocol (add flow diagram for stop protocol)

### ISSUE THREAD

**Issue by abutenkolamden** [Lamden/cilantro#429]

**Comment by JeffWScott** [comment]
@raghupc it's unclear in the doco how the stop protocol is initiated.

**Comment by raghupc** [comment]
I have this in the doc about when it needs stop protocol:
It needs to go down for maintenance or system upgrades
It wants to leave the network
The number of active nodes came down below min-quorum required and so no work can be done.

When one of them met, it simply calls shutdown and follow the steps shown in the diagram

**Comment by abutenkolamden** [comment]
@JeffWScott do you feel documentation needs some changes based on Raghu's answer or we can close?

**Comment by JeffWScott** [comment]
@raghupc okay so it sounds like this is an automatic process, and not something initiated by the node owner.  That's makes sense.

@abutenkolamden please move to Done
