### ISSUE TITLE
Documentation - describe Errors and Recovery of the system

### ISSUE THREAD

**Issue by abutenkolamden** [Lamden/cilantro#430]
Feedback from team may drive the scope of work

Acceptance criteria - confirmation from other team members (at least Jeff) that documentation is Ok to understand the product for a new developer.

**Comment by JeffWScott** [comment]
@raghupc this section seems light on Errors is there really only 3 Error situations?

**Comment by abutenkolamden** [comment]
@raghupc ?

**Comment by raghupc** [comment]
yes, they are 3 main classes of errors each has to deal with various issues.

**Comment by abutenkolamden** [comment]
@raghupc @JeffWScott should we cover more or stop on 3 main classes?

**Comment by JeffWScott** [comment]
@raghupc sound good, just checking.
@abutenkolamden please move to Done
