### ISSUE TITLE
Documentation - add Data flows and show transaction life cycle

### ISSUE THREAD

**Issue by abutenkolamden** [Lamden/cilantro#431]
Feedback from team may drive the scope of work

Acceptance criteria - confirmation from other team members (at least Jeff) that documentation is Ok to understand the product for a new developer.

**Comment by JeffWScott** [comment]
Transaction Lifecycle:
- User's submit transactions via a Masternodes webserver.  Any Masternode can be an entry to the network. 
- Masternodes queue these transactions and make them available to the Transaction Batcher process
- The Transaction Batcher process makes batches of transactions and publishes them for the delegates to retrieve.
- Delegates use Sub Block Builder processes to take the transaction batches and processes them. First by executing all the transactions in the batch and then going through a conflict resolution process by comparing them to other Sub Block Builders.
- The Sub Block Builders send these batches back to the Masternodes as Sub Block Contenders.
- The Masternodes aggregate them basked on their sub-block number and root hash of the sub-block.
    - if consensus is not met due to transactions being misaligned then a message will be sent back to the sub block builders to try and align their batches to the same state
    - if consensus is not met because the results differ then a message will be sent back to the delegates to sync their states using the "catch-up process"
   - A timeout counter is started when the first Sub Block is received and if the timeout trips then quorum requirements will be evaluated.
    - If all sub-blocks meet consensus they are formed into a block and saved into the blockchain


@raghupc if this is correct please have @abutenkolamden close

**Comment by abutenkolamden** [comment]
@raghupc ?

**Comment by raghupc** [comment]
correct
