### ISSUE TITLE
Documentation - explain Partial Block concept

### ISSUE THREAD

**Issue by abutenkolamden** [Lamden/cilantro#432]
Feedback from team may drive the scope of work

Acceptance criteria - confirmation from other team members (at least Jeff) that documentation is Ok to understand the product for a new developer.

**Comment by JeffWScott** [comment]
- A block is made up of sub blocks
- currently if 1 sub-block is out of consensus we send a failed block notification.
- we should actually create a block our of all the sub blocks that are in consensus, up-to the sub-block that is out of consensus
- for example if a block is made up of 10 sub blocks and it's the 8th sub-block that is out of consensus, then we would make the block out of the first 7 and send a "partial-block" notification to the delegates and have them act accordingly.

@raghupc if this is correct please have @abutenkolamden close

**Comment by abutenkolamden** [comment]
@raghupc ?

**Comment by raghupc** [comment]
correct
