### ISSUE TITLE
Documentation - describe Sub-block Client

### ISSUE THREAD

**Issue by abutenkolamden** [Lamden/cilantro#442]
Feedback from team may drive the scope of work

Acceptance criteria - confirmation from other team members (at least Jeff) that documentation is Ok to understand the product for a new developer.

**Comment by JeffWScott** [comment]
"Contracting client is where transactions are executed. It manages the db and cache layers as well as enables concurrent executions of multiple transaction batches."

The section is very descriptive @abutenkolamden please move to done.
