### ISSUE TITLE
Documentation - describe Sub-block

### ISSUE THREAD

**Issue by abutenkolamden** [Lamden/cilantro#444]
Feedback from team may drive the scope of work

Acceptance criteria - confirmation from other team members (at least Jeff) that documentation is Ok to understand the product for a new developer.

**Comment by JeffWScott** [comment]
- A Sub Block is created from transaction batches retrieved from the masternode
- A Sub Block Builder (SBB) is a process assigned to each Sub Block to run and resolve conflicts in its transactions.
- Sub Block Builders run in parallel with other SBBs and resolve conflicts sequentially after all have run.
- After conflict resolution the Sub Block is sent to the masternode as a Sub Block Contender
- If the masternode finds the Sub Block Contender in Consensus then it is committed the the Delegates Database (DBD)

@raghupc if this is correct please have @abutenkolamden close

**Comment by abutenkolamden** [comment]
@raghupc ?

**Comment by raghupc** [comment]
yes, it is correct. please close it
