### ISSUE TITLE
Documentation - describe Conflict Resolution

### ISSUE THREAD

**Issue by abutenkolamden** [Lamden/cilantro#445]
Feedback from team may drive the scope of work

Acceptance criteria - confirmation from other team members (at least Jeff) that documentation is Ok to understand the product for a new developer.

**Comment by JeffWScott** [comment]
Lets see if I understand this:
- This is a delegate process
- A Sub Block is a batch of transactions that need to be run.  A Sub Block builder is a process assigned to each Sub Block to run its transactions.
- First comes the execution phase where all Sub Block Builders (SBB) run the batch of transactions inside of them, in parallel with the other Sub Block Builder Processes. 
- This execution is done directly against the Delegate's Database (DBD) which is the gold source for current state on the Delegate.  Execution state changes are stored in the SBB's "layer 3"cache called the "Local Cache" (LCD). This is a state that is local and contained to each SBB.
- Once all the Sub Block Builders have finished executing they are run in a sequential order.  Each Sub block was pre-indexed before the execution phase, so it know where it is in the run order.
- As the LCD state in each SBB is read it updates the "layer 2" "Common Cache" (CCD) which is now going to be a shared state and resolution layer between all Sub Blocks states.
- When updating the CCD if a SBB finds that a key already exists and it has a different value than what was used when it ran a particular tx, then it reruns that tx with the updated value from CCD and then updates the CCD with all of it's new values.  This process continues until all Sub Block Builders have updated the CCD.
- This process allows parallel execution of transactions in a high percentage of situations
- Once conflict resolution is done the Sub Block is packages and sent to the masternode as a "Sub Block Contender" to be compared to the Sub Blocks created by all other Delegates.
- If 2/3 of the delegates came up with the same value, then this sub block is committed to a block.

**Comment by raghupc** [comment]
Yes, you described the flow accurately.

**Comment by JeffWScott** [comment]
@abutenkolamden please close
