### ISSUE TITLE
Documentation - add flow chart for sub-block builder

### ISSUE THREAD

**Issue by abutenkolamden** [Lamden/cilantro#447]
Feedback from team may drive the scope of work

Acceptance criteria - confirmation from other team members (at least Jeff) that documentation is Ok to understand the product for a new developer.

**Comment by JeffWScott** [comment]
Moved SBB flow chart to SBB section (was at bottom of page).

If you agree @raghupc then please have @abutenkolamden close issue

**Comment by abutenkolamden** [comment]
@raghupc ?

**Comment by raghupc** [comment]
I have no issue with that. we can close it.
