### ISSUE TITLE
Preliminary Consensus Setup

### ISSUE THREAD

**Issue by StuartFarmer** [Lamden/cilantro#6]
Create a basic delegate such that:

- [ ] subscribes to delegate messages
- [ ] compares message to local SHA3 hash of current bundle
- [ ] verifies signature is a legitimate delegate (hard code now)
- [ ] wait for 51% of delegates to return the same hash with proper signature

**Comment by Denton24646** [comment]
ahh now I see 51% is the key, gotcha!
