### ISSUE TITLE
Modify ZMQ connection flow on Witness.py

### ISSUE THREAD

**Issue by StuartFarmer** [Lamden/cilantro#7]
Two things stood out to me on the code. Looking legit otherwise.

1. https://github.com/Lamden/cilantro/blob/networking/cilantro/networking/witness.py#L57
The context and port should be defined prior in the constructor of the class rather than on the fly. Because the port is not being bound at this point in time, we aren't blocking or opening any ports when we just declare the context and host.

Doing this will save time and will allow us to 'bind' whenever we want across the whole class in case new features demand it without having to redeclare the context.

2. https://github.com/Lamden/cilantro/blob/networking/cilantro/networking/witness.py#L67
After the message has been processed, we need to unbind the port. We also may come into issues using 'bind' instead of 'connect' but I'm not 100% that's true.

**Comment by Denton24646** [comment]
Gotcha - will update
